#include "model/ModelRenderer.h"
#include "renderer/backend/opengl/OpenGLDebug.h"
#include "model/ModelRenderLogic.h"
#include "renderer/Shader.h"
#include "core/Window.h"
#include <array>
#include <cstddef>
#include <stdexcept>
#include <utility>

namespace model {
ModelRenderer::~ModelRenderer(){ clear(); }
void ModelRenderer::initialize(const std::filesystem::path& root,bool srgb,GraphicsApi api){m_framebufferSrgb=srgb;m_vertexAttribIPointer=reinterpret_cast<VertexAttribIPointerFn>(Window::graphicsProcAddress("glVertexAttribIPointer"));if(!m_vertexAttribIPointer)throw std::runtime_error("OpenGL integer vertex attributes are unavailable");m_shader=std::make_unique<Shader>(root/"shaders/model.vert",root/"shaders/model.frag",api);}
ModelHandle ModelRenderer::upload(std::shared_ptr<const ModelAsset> asset){
 if(!asset) throw std::invalid_argument("cannot upload a null model asset");
 GpuModel gpu;gpu.asset=std::move(asset);
 for(const ImageData& image:gpu.asset->images){GLuint t=0;GL_CHECK(glGenTextures(1,&t));GL_CHECK(glBindTexture(GL_TEXTURE_2D,t));GL_CHECK(glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST));GL_CHECK(glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST));GL_CHECK(glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE));GL_CHECK(glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE));GL_CHECK(glTexImage2D(GL_TEXTURE_2D,0,GL_SRGB8_ALPHA8,image.width,image.height,0,GL_RGBA,GL_UNSIGNED_BYTE,image.pixels.data()));gpu.textures.push_back(t);}
 std::vector<int> nodes(gpu.asset->primitives.size(),-1);for(std::size_t n=0;n<gpu.asset->nodes.size();++n)for(int p:gpu.asset->nodes[n].primitives)if(p>=0&&static_cast<std::size_t>(p)<nodes.size())nodes[static_cast<std::size_t>(p)]=static_cast<int>(n);
 for(std::size_t i=0;i<gpu.asset->primitives.size();++i){const Primitive& s=gpu.asset->primitives[i];GpuPrimitive p;p.indexCount=static_cast<GLsizei>(s.indices.size());p.material=s.material;p.skin=s.skin;p.node=nodes[i];GL_CHECK(glGenVertexArrays(1,&p.vao));GL_CHECK(glGenBuffers(1,&p.vbo));GL_CHECK(glGenBuffers(1,&p.ebo));GL_CHECK(glBindVertexArray(p.vao));GL_CHECK(glBindBuffer(GL_ARRAY_BUFFER,p.vbo));GL_CHECK(glBufferData(GL_ARRAY_BUFFER,static_cast<GLsizeiptr>(s.vertices.size()*sizeof(Vertex)),s.vertices.data(),GL_STATIC_DRAW));GL_CHECK(glBindBuffer(GL_ELEMENT_ARRAY_BUFFER,p.ebo));GL_CHECK(glBufferData(GL_ELEMENT_ARRAY_BUFFER,static_cast<GLsizeiptr>(s.indices.size()*sizeof(uint32_t)),s.indices.data(),GL_STATIC_DRAW));GL_CHECK(glEnableVertexAttribArray(0));GL_CHECK(glVertexAttribPointer(0,3,GL_FLOAT,GL_FALSE,sizeof(Vertex),reinterpret_cast<void*>(offsetof(Vertex,position))));GL_CHECK(glEnableVertexAttribArray(1));GL_CHECK(glVertexAttribPointer(1,3,GL_FLOAT,GL_FALSE,sizeof(Vertex),reinterpret_cast<void*>(offsetof(Vertex,normal))));GL_CHECK(glEnableVertexAttribArray(2));GL_CHECK(glVertexAttribPointer(2,2,GL_FLOAT,GL_FALSE,sizeof(Vertex),reinterpret_cast<void*>(offsetof(Vertex,uv))));GL_CHECK(glEnableVertexAttribArray(3));GL_CHECK(m_vertexAttribIPointer(3,4,GL_UNSIGNED_INT,sizeof(Vertex),reinterpret_cast<void*>(offsetof(Vertex,joints))));GL_CHECK(glEnableVertexAttribArray(4));GL_CHECK(glVertexAttribPointer(4,4,GL_FLOAT,GL_FALSE,sizeof(Vertex),reinterpret_cast<void*>(offsetof(Vertex,weights))));gpu.primitives.push_back(p);}GL_CHECK(glBindVertexArray(0));m_models.push_back(std::move(gpu));return static_cast<ModelHandle>(m_models.size());}
void ModelRenderer::queue(const ModelDraw& d){if(d.model&&d.model<=m_models.size())m_draws.push_back(d);}
void ModelRenderer::flushOpaque(const glm::mat4& v,const RenderEnvironment& e,const glm::vec3& c,float s,float f){flush(false,v,e,c,s,f);}
void ModelRenderer::flushBlend(const glm::mat4& v,const RenderEnvironment& e,const glm::vec3& c,float s,float f){sortBlended(m_draws);flush(true,v,e,c,s,f);m_draws.clear();}
void ModelRenderer::flush(bool blended,const glm::mat4& vp,const RenderEnvironment& env,const glm::vec3& camera,float fogStart,float fogEnd){if(!m_shader)return;GLboolean oldBlend=GL_FALSE,oldCull=GL_FALSE,oldDepth=GL_TRUE;GL_CHECK(glGetBooleanv(GL_BLEND,&oldBlend));GL_CHECK(glGetBooleanv(GL_CULL_FACE,&oldCull));GL_CHECK(glGetBooleanv(0x0B72,&oldDepth));if(blended){GL_CHECK(glEnable(GL_BLEND));GL_CHECK(glBlendFunc(GL_SRC_ALPHA,GL_ONE_MINUS_SRC_ALPHA));GL_CHECK(glDepthMask(GL_FALSE));}m_shader->bind();m_shader->setMat4("uViewProjection",vp);m_shader->setVec3("uCameraPosition",camera);m_shader->setVec3("uAmbientColor",env.ambientColor*env.ambientIntensity);m_shader->setVec3("uDirectColor",env.directColor*env.directIntensity);m_shader->setVec3("uLightDirection",env.lightDirection);m_shader->setVec3("uFogColor",env.fogColor);m_shader->setFloat("uFogStart",fogStart);m_shader->setFloat("uFogEnd",fogEnd);m_shader->setInt("uManualGamma",m_framebufferSrgb?0:1);m_shader->setInt("uTexture",0);std::array<glm::mat4,MAX_JOINTS> identity;identity.fill(glm::mat4(1));
 for(const ModelDraw& d:m_draws){const GpuModel& g=m_models[d.model-1];for(const GpuPrimitive& p:g.primitives){const Material fallback;const Material& mat=p.material>=0&&static_cast<std::size_t>(p.material)<g.asset->materials.size()?g.asset->materials[static_cast<std::size_t>(p.material)]:fallback;if((modelPass(mat.alphaMode)==ModelPass::Blend)!=blended)continue;glm::mat4 node=d.instance&&p.node>=0&&static_cast<std::size_t>(p.node)<d.instance->pose.global.size()?d.instance->pose.global[static_cast<std::size_t>(p.node)]:glm::mat4(1);m_shader->setMat4("uModel",d.transform);m_shader->setMat4("uNode",p.skin>=0?glm::mat4(1):node);const std::vector<glm::mat4>* palette=nullptr;if(d.instance&&p.skin>=0&&static_cast<std::size_t>(p.skin)<d.instance->jointPalettes.size())palette=&d.instance->jointPalettes[static_cast<std::size_t>(p.skin)];m_shader->setMat4Array("uJoints[0]",palette&&!palette->empty()?palette->data():identity.data(),palette&&!palette->empty()?palette->size():identity.size());m_shader->setVec4("uBaseColor",mat.baseColor*d.tint);m_shader->setFloat("uAlphaCutoff",mat.alphaMode==AlphaMode::Mask?mat.alphaCutoff:0);const bool textured=mat.image>=0&&static_cast<std::size_t>(mat.image)<g.textures.size();m_shader->setInt("uUseTexture",textured?1:0);if(textured){GL_CHECK(glActiveTexture(GL_TEXTURE0));GL_CHECK(glBindTexture(GL_TEXTURE_2D,g.textures[static_cast<std::size_t>(mat.image)]));}if(mat.doubleSided)GL_CHECK(glDisable(GL_CULL_FACE));else GL_CHECK(glEnable(GL_CULL_FACE));GL_CHECK(glBindVertexArray(p.vao));GL_CHECK(glDrawElements(GL_TRIANGLES,p.indexCount,GL_UNSIGNED_INT,nullptr));}}
 GL_CHECK(glBindVertexArray(0));m_shader->unbind();if(oldBlend)GL_CHECK(glEnable(GL_BLEND));else GL_CHECK(glDisable(GL_BLEND));if(oldCull)GL_CHECK(glEnable(GL_CULL_FACE));else GL_CHECK(glDisable(GL_CULL_FACE));GL_CHECK(glDepthMask(oldDepth));}
void ModelRenderer::clear(){m_draws.clear();for(GpuModel& g:m_models){for(GpuPrimitive& p:g.primitives){if(p.ebo)GL_CHECK(glDeleteBuffers(1,&p.ebo));if(p.vbo)GL_CHECK(glDeleteBuffers(1,&p.vbo));if(p.vao)GL_CHECK(glDeleteVertexArrays(1,&p.vao));}for(GLuint t:g.textures)if(t)GL_CHECK(glDeleteTextures(1,&t));}m_models.clear();}
} // namespace model
