'use strict';
const $=id=>document.getElementById(id);
let shownColor="";
let state, samples, allSamples=[], playing=true, frame=0, requestId=0, yaw=.55,pitch=.35;
const status=message=>{$('status').textContent=message;};
async function api(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await response.json();if(!response.ok)throw Error(data.error);return data;}
function spec(){return state.document.materials[$('material').value];}
function fill(select,values,value){select.replaceChildren(...values.map(v=>{const option=document.createElement('option');option.value=v;option.textContent=v;return option;}));if(value!==undefined)select.value=value;}
function updateLocked(){$('locked').textContent=state.locked[$('material').value]!==undefined?'已锁定种子 '+state.locked[$('material').value]:'此材质尚未锁定';$('lock').textContent=state.locked[$('material').value]!==undefined?'解除锁定':'锁定候选';}
function loadMaterial(){const s=spec();$('variants').value=s.variants||1;$('frames').value=s.animation?.frames||1;$('fps').value=s.animation?.fps||0;fill($('variant'),Array.from({length:+$('variants').value},(_,i)=>String(i)),'0');fill($('recipe'),Object.keys({...state.document.recipes,...state.document.examples}),s.recipe);updateLayers();$('role').value=2;loadColor();updateLocked();refresh();}
function recipeLayers(name=$('recipe').value,seen=[]){if(seen.includes(name))throw Error('循环配方');const r={...state.document.recipes,...state.document.examples}[name];return [...(r.parent?recipeLayers(r.parent,[...seen,name]):[]),...(r.layers||[])];}
function updateLayers(){const layers=recipeLayers();$('layers').value=JSON.stringify(layers,null,2);fill($('layer'),layers.map((l,i)=>`${i}: ${l.op}`));loadLayer();}
function loadLayer(){const layers=JSON.parse($('layers').value),l=layers[$('layer').selectedIndex]||{};for(const [id,key,d] of [['density','density',.2],['scale','scale',1],['role','role',2],['layerSeed','seed',0]])$(id).value=l[key]??d;loadColor();}
function loadColor(){const colors=spec().palette||state.palettes[$('material').value],c=colors[+$('role').value];if(c){$('color').value='#'+c.slice(0,3).map(x=>x.toString(16).padStart(2,'0')).join('');shownColor=$('color').value;}}
function customLayers(layers){const name='draft_'+$('material').value;state.document.recipes[name]={layers};spec().recipe=name;fill($('recipe'),Object.keys({...state.document.recipes,...state.document.examples}),name);$('layers').value=JSON.stringify(layers,null,2);}
function settings(){const s=spec();const layers=JSON.parse($('layers').value),l=layers[$('layer').selectedIndex];if(l&&l.op!=='base'){let changed=false;for(const [key,id,defaultValue] of [['density','density',.2],['scale','scale',1],['role','role',2],['seed','layerSeed',0]]){const value=+$(id).value;if(value!==(l[key]??defaultValue)){l[key]=value;changed=true;}}if(changed)customLayers(layers);}const hex=$('color').value,role=+$('role').value;if(hex!==shownColor){s.palette=structuredClone(s.palette||state.palettes[$('material').value]);if(!s.palette[role])throw Error('角色超出调色板');s.palette[role]=[parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16),s.palette[role][3]];shownColor=hex;}s.variants=+$('variants').value;if((s.preferred_variant||0)>=s.variants)s.preferred_variant=0;s.recipe=$('recipe').value;const n=+$('frames').value;s.animation={frames:n,fps:n>1?+$('fps').value:0,loop:'repeat'};state.seed=$('seed').value;}
async function refresh(){const id=++requestId;try{settings();status('正在生成…');const data=await api('/api/preview',{document:state.document,material:$('material').value,seed:state.seed,variant:+$('variant').value});if(id!==requestId)return;samples=data.frames;allSamples=data.variants;frame=0;$('frame').max=samples.length-1;fill($('mask'),Object.keys(samples[0].masks));uploadTextures();draw2d();status('预览已更新 · '+allSamples.length+' 个变体 · '+samples.length+' 帧');}catch(error){status(error.message);}}
function drawPixels(canvas,pixels,size=16){const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;const tmp=document.createElement('canvas');tmp.width=tmp.height=16;tmp.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(pixels.flat()),16,16),0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(tmp,0,0,size,size);}
function draw2d(){if(!samples)return;frame=Math.min(frame,samples.length-1);const s=samples[frame],channel=$('channel').value;drawPixels($('native'),s[channel]);drawPixels($('large'),s[channel],192);const mask=s.masks[$('mask').value]||s.masks.coverage;drawPixels($('maskCanvas'),mask.map(v=>v?[166,220,160,255]:[29,43,45,255]),192);$('frame').value=frame;$('frameLabel').textContent=frame+' / '+samples.length;}
let gl,program,vao,textures=[],uniforms={};
function initializeGL(){gl=$('preview').getContext('webgl2',{alpha:false});if(!gl){$('fallback').hidden=false;return;}
const vertex=`#version 300 es
precision highp float;const vec2 points[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));out vec2 screen;void main(){screen=points[gl_VertexID];gl_Position=vec4(screen,0,1);}`;
const fragment=`#version 300 es
precision highp float;precision highp sampler2DArray;in vec2 screen;out vec4 color;
uniform sampler2DArray colors;uniform sampler2DArray normals;uniform sampler2DArray properties;
uniform int viewMode;uniform int channel;uniform int lightMode;uniform int animationFrame;uniform int frameCount;uniform int variantCount;uniform int selectedVariant;uniform vec2 rotation;uniform float aspect;
vec3 decode(vec3 c){return mix(c/12.92,pow((c+.055)/1.055,vec3(2.4)),step(vec3(.04045),c));}
vec3 encode(vec3 c){return mix(c*12.92,1.055*pow(max(c,vec3(0)),vec3(1./2.4))-.055,step(vec3(.0031308),c));}
void main(){vec2 s=screen*vec2(aspect,1);vec3 bg=mix(vec3(.08,.12,.14),vec3(.15,.22,.23),clamp(screen.y*.4+.5,0.,1.));vec2 uv;vec3 n=vec3(0,0,1),t=vec3(1,0,0),b=vec3(0,1,0);int variant=selectedVariant;
if(viewMode==1){uv=s*3.+vec2(3.5,2.5);if(any(greaterThan(abs(s),vec2(1.4,.85)))){color=vec4(bg,1);return;}ivec2 cell=ivec2(floor(uv));variant=(abs(cell.x*17+cell.y*31)%variantCount);}
else if(viewMode==2){uv=s*.65+.5;if(any(lessThan(uv,vec2(0)))||any(greaterThan(uv,vec2(1)))){color=vec4(bg,1);return;}}
else{float cy=cos(rotation.x),sy=sin(rotation.x),cx=cos(rotation.y),sx=sin(rotation.y);mat3 ry=mat3(cy,0,-sy,0,1,0,sy,0,cy),rx=mat3(1,0,0,0,cx,sx,0,-sx,cx);mat3 r=ry*rx;vec3 ro=r*vec3(0,0,3.4),rd=r*normalize(vec3(s,-2.8));vec3 v0=(-vec3(.8)-ro)/rd,v1=(vec3(.8)-ro)/rd;vec3 near=min(v0,v1),far=max(v0,v1);float entry=max(max(near.x,near.y),near.z),exit=min(min(far.x,far.y),far.z);if(entry>exit||entry<0.){color=vec4(bg,1);return;}vec3 p=ro+rd*entry;n=vec3(0);if(near.x>=near.y&&near.x>=near.z){n.x=-sign(rd.x);uv=vec2(p.z*n.x,p.y)/1.6+.5;t=vec3(0,0,n.x);b=vec3(0,1,0);}else if(near.y>=near.z){n.y=-sign(rd.y);uv=vec2(p.x,-p.z*n.y)/1.6+.5;t=vec3(1,0,0);b=vec3(0,0,-n.y);}else{n.z=-sign(rd.z);uv=vec2(p.x*n.z,p.y)/1.6+.5;t=vec3(n.z,0,0);b=vec3(0,1,0);}}
vec2 tile=fract(uv);tile.y=1.-tile.y;float layer=float(variant*frameCount+animationFrame);vec4 a=texture(colors,vec3(tile,layer)),p=texture(properties,vec3(tile,layer));vec3 normal=texture(normals,vec3(tile,layer)).xyz;
if(channel>0){vec3 c=channel==1?normal:channel==2?p.rgb:vec3(p.a);color=vec4(c,1);return;}
vec3 linear=decode(a.rgb);if(viewMode!=2){n=normalize(t*(normal.x*2.-1.)+b*(normal.y*2.-1.)+n*(normal.z*2.-1.));vec3 l=normalize(vec3(-.4,.8,1.));vec3 ambient=lightMode==0?vec3(.45):lightMode==1?vec3(.18,.16,.23):vec3(.055,.07,.10);vec3 direct=lightMode==0?vec3(.8,.78,.7):lightMode==1?vec3(.9,.38,.17):vec3(.12,.2,.3);float spec=pow(max(dot(n,normalize(l+vec3(0,0,1))),0.),mix(100.,5.,p.r));linear*=ambient+direct*max(dot(n,l),0.);linear+=direct*spec*mix(vec3(.04),decode(a.rgb),p.g);linear+=decode(a.rgb)*p.b*1.4;}
vec3 checker=mix(bg,bg*1.4,mod(floor(uv.x*16.)+floor(uv.y*16.),2.));color=vec4(mix(checker,encode(linear),a.a),1);}`;
function compile(type,source){const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(shader));return shader;}
program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,vertex));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);vao=gl.createVertexArray();gl.bindVertexArray(vao);for(const name of ['colors','normals','properties','viewMode','channel','lightMode','animationFrame','frameCount','variantCount','selectedVariant','rotation','aspect'])uniforms[name]=gl.getUniformLocation(program,name);textures=[0,1,2].map(()=>gl.createTexture());}
function uploadTextures(){if(!gl||!samples)return;gl.useProgram(program);for(const [index,key] of ['pixels','normal','property'].entries()){gl.activeTexture(gl.TEXTURE0+index);gl.bindTexture(gl.TEXTURE_2D_ARRAY,textures[index]);const bytes=new Uint8Array(allSamples.flatMap(v=>v.flatMap(f=>f[key].flat())));gl.texImage3D(gl.TEXTURE_2D_ARRAY,0,gl.RGBA8,16,16,allSamples.length*samples.length,0,gl.RGBA,gl.UNSIGNED_BYTE,bytes);gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.uniform1i(uniforms[['colors','normals','properties'][index]],index);}}
let last=-1;
function render(time){if(samples){const fps=spec().animation?.fps||0;if(playing&&fps){frame=Math.floor(time/1000*fps)%samples.length;if(frame!==last){draw2d();last=frame;}}if(gl){gl.viewport(0,0,gl.canvas.width,gl.canvas.height);gl.useProgram(program);gl.uniform1i(uniforms.viewMode,{cube:0,wall:1,flat:2}[$('view').value]);gl.uniform1i(uniforms.channel,{pixels:0,normal:1,property:2,height:3}[$('channel').value]);gl.uniform1i(uniforms.lightMode,{day:0,dusk:1,cave:2}[$('light').value]);gl.uniform1i(uniforms.animationFrame,frame);gl.uniform1i(uniforms.frameCount,samples.length);gl.uniform1i(uniforms.variantCount,allSamples.length);gl.uniform1i(uniforms.selectedVariant,+$('variant').value);gl.uniform2f(uniforms.rotation,yaw,pitch);gl.uniform1f(uniforms.aspect,gl.canvas.width/gl.canvas.height);gl.drawArrays(gl.TRIANGLES,0,3);}else{const c=$('preview').getContext('2d');c.imageSmoothingEnabled=false;c.clearRect(0,0,760,520);c.drawImage($('large'),230,110,300,300);}}requestAnimationFrame(render);}
$('material').onchange=loadMaterial;$('recipe').onchange=()=>{spec().recipe=$('recipe').value;updateLayers();refresh();};$('layer').onchange=loadLayer;$('role').onchange=()=>{loadColor();try{const layers=JSON.parse($('layers').value),l=layers[$('layer').selectedIndex];if(l.op!=='base'){l.role=+$('role').value;customLayers(layers);refresh();}}catch(e){status(e.message);}};
for(const id of ['density','scale','layerSeed'])$(id).onchange=()=>{try{const layers=JSON.parse($('layers').value),l=layers[$('layer').selectedIndex];if(l.op==='base')return;for(const [key,input] of [['density','density'],['scale','scale'],['role','role'],['seed','layerSeed']])l[key]=+$(input).value;customLayers(layers);refresh();}catch(e){status(e.message);}};
$('color').onchange=()=>{const s=spec();s.palette=structuredClone(s.palette||state.palettes[$('material').value]);const hex=$('color').value;s.palette[+$('role').value]=[parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16),s.palette[+$('role').value][3]];refresh();};
$('applyLayers').onclick=()=>{try{customLayers(JSON.parse($('layers').value));updateLayers();refresh();}catch(e){status(e.message);}};
$('refresh').onclick=refresh;$('variant').onchange=refresh;$('variants').onchange=()=>{fill($('variant'),Array.from({length:Math.max(1,Math.min(4,+$('variants').value))},(_,i)=>String(i)),'0');refresh();};
$('channel').onchange=draw2d;$('mask').onchange=draw2d;$('frame').oninput=()=>{playing=false;frame=+$('frame').value;$('play').textContent='播放';draw2d();};$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'暂停':'播放';};
$('lock').onclick=()=>{const n=$('material').value;if(state.locked[n]!==undefined){delete state.locked[n];delete spec().preferred_variant;}else{state.locked[n]=$('seed').value;spec().preferred_variant=(+$('variant').value+(spec().preferred_variant||0))%spec().variants;$('variant').value='0';}updateLocked();refresh();};
async function persist(path,apply=false){try{settings();status('正在处理…');const result=await api(path,{document:state.document,seed:state.seed,locked:state.locked,apply});status(result.exported?'已导出 '+result.exported+(result.applied?' · 正式资产已更新':''):'草稿已保存');}catch(e){status(e.message);}}
$('save').onclick=()=>persist('/api/save');$('export').onclick=()=>persist('/api/export');$('apply').onclick=()=>persist('/api/export',true);
let drag;$('preview').onpointerdown=e=>{drag=[e.clientX,e.clientY];$('preview').setPointerCapture(e.pointerId);};$('preview').onpointermove=e=>{if(drag){yaw+=(e.clientX-drag[0])*.01;pitch=Math.max(-1.3,Math.min(1.3,pitch+(e.clientY-drag[1])*.01));drag=[e.clientX,e.clientY];}};$('preview').onpointerup=()=>drag=null;
(async()=>{try{state=await api('/api/state');$('seed').value=state.seed;fill($('material'),state.materials,'stone');try{initializeGL();}catch(e){gl=null;$('fallback').hidden=false;status('三维预览不可用: '+e.message);}loadMaterial();requestAnimationFrame(render);}catch(e){status(e.message);}})();
