cmake_minimum_required(VERSION 3.16)
include("${CMAKE_CURRENT_LIST_DIR}/project_version.cmake")

if("$ENV{GITHUB_REF}" MATCHES "^refs/tags/v" AND
   NOT "$ENV{GITHUB_REF_NAME}" STREQUAL "${MINECRAFTC_RELEASE_TAG}")
    message(FATAL_ERROR
        "Release tag '$ENV{GITHUB_REF_NAME}' must exactly match VERSION as '${MINECRAFTC_RELEASE_TAG}'")
endif()
if(NOT "$ENV{GITHUB_OUTPUT}" STREQUAL "")
    file(APPEND "$ENV{GITHUB_OUTPUT}"
        "version=${MINECRAFTC_VERSION}\nchannel=${MINECRAFTC_VERSION_CHANNEL}\nprerelease=${MINECRAFTC_VERSION_PRERELEASE}\nrelease_tag=${MINECRAFTC_RELEASE_TAG}\n")
endif()
if(NOT "$ENV{GITHUB_ENV}" STREQUAL "")
    file(APPEND "$ENV{GITHUB_ENV}"
        "MINECRAFTC_VERSION=${MINECRAFTC_VERSION}\nMINECRAFTC_VERSION_CORE=${MINECRAFTC_VERSION_CORE}\nMINECRAFTC_VERSION_DISPLAY=${MINECRAFTC_VERSION_DISPLAY}\nMINECRAFTC_VERSION_CODE=${MINECRAFTC_VERSION_CODE}\nRELEASE_DIR=MinecraftC-${MINECRAFTC_VERSION}\n")
endif()
